[package]
name = "opcuad"
version = "0.1.0"
authors = ["Gabriel Malkas <gabriel@beaverlabs.net>"]
edition = "2018"

[dependencies]
opcua-client = { git = "https://github.com/locka99/opcua" }
opcua-console-logging = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
